//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextExam2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ProductName { get; set; }
        public int IdProductType { get; set; }
        public string Image { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
